# Generated by Django 3.2.12 on 2025-04-10 11:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('middle_name', models.CharField(blank=True, help_text='Optional middle name', max_length=50, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone_number', models.CharField(db_index=True, help_text='Format: +1234567890', max_length=15, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Valid email address required', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField(db_index=True, help_text='Full postal address')),
                ('file_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', help_text='Current file status', max_length=6)),
                ('file_number', models.CharField(db_index=True, help_text='Unique file identifier', max_length=20, unique=True)),
                ('client_status', models.CharField(choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], db_index=True, default='ALIVE', help_text='Current client status', max_length=8)),
                ('company', models.CharField(blank=True, db_index=True, help_text='Associated company if applicable', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('linked_clients', models.ManyToManyField(blank=True, help_text='Other contacts related to this one', related_name='linked_contacts', to='contacts.Contact', verbose_name='Linked Clients')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='contacts_co_search__95f1b5_gin'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name', 'last_name'], name='contacts_co_first_n_57a3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['file_number'], name='contacts_co_file_nu_997b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='contacts_co_last_na_bb56ce_idx'),
        ),
    ]
