# Generated by Django 4.2.20 on 2025-04-12 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_last_na_bb56ce_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(db_index=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client_status',
            field=models.CharField(choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], db_index=True, default='ALIVE', max_length=8, verbose_name='client status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='file_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='file number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='file_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=6, verbose_name='file status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linked_clients',
            field=models.ManyToManyField(blank=True, related_name='linked_contacts', to='contacts.contact', verbose_name='linked clients'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client_status'], name='contacts_co_client__a9dee9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['file_status'], name='contacts_co_file_st_aad4f7_idx'),
        ),
    ]
